model_name: "GSAI-ML/LLaDA-8B-Instruct"    # 预训练模型名称
local_batch_size: 1                        # 训练批次大小
max_length: 4096                           # 分词最大长度
num_epochs: 20                             # 训练轮数
learning_rate: 1e-5                        # 优化器学习率
grad_accum_steps: 1                        # 梯度累积步数
output_dir: "./sft_save"                   # 模型与日志保存目录
job_name: "llada-sft"                      # 任务名称
train_data: "simplescaling/s1K"            # 训练数据路径
max_grad_norm: 1.0                         # 梯度裁剪阈值
weight_decay: 0.1                          # 权重衰减
evaluation_strategy: "steps"               # 评估策略
eval_steps: 100                            # 评估步数
logging_steps: 10                          # 日志记录步数
save_steps: 100                            # 保存步数
save_total_limit: 20                       # 最大保存检查点数量
load_best_model_at_end: true              # 训练结束时加载最佳模型
bf16: true                                 # 使用bfloat16精度
report_to: "none"                          # 报告工具，在配置完成 wandb 之后，可选"wandb"
remove_unused_columns: false               # 是否移除未使用的列